# Generated by Django 5.1.7 on 2025-09-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food & Dining'), ('TRANSPORT', 'Transportation'), ('ENTERTAINMENT', 'Entertainment'), ('SHOPPING', 'Shopping'), ('UTILITIES', 'Utilities'), ('HEALTHCARE', 'Healthcare'), ('TRAVEL', 'Travel'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], default='OTHER', max_length=15),
        ),
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this expense'),
        ),
    ]
