export const mockUsers = [
  { user_id: 1, email: "john@example.com", password: "password123", name: "John Doe" },
  { user_id: 2, email: "jane@example.com", password: "password123", name: "Jane Smith" },
  { user_id: 3, email: "bob@example.com", password: "password123", name: "Bob Johnson" },
  { user_id: 4, email: "alice@example.com", password: "password123", name: "Alice Brown" },
  { user_id: 5, email: "charlie@example.com", password: "password123", name: "Charlie Wilson" },
]

export const mockConversations = [
  {
    conversation_id: 1,
    type: "direct",
    name: null,
    created_by: 1,
    created_at: "2024-01-01T10:00:00Z",
    updated_at: "2024-01-01T15:30:00Z",
    participants: [
      { user_id: 1, name: "John Doe", role: "member" },
      { user_id: 2, name: "Jane Smith", role: "member" },
    ],
    last_message: "Hey, how are you doing?",
    unread_count: 2,
    is_muted: false,
  },
  {
    conversation_id: 2,
    type: "group",
    name: "Team Project",
    created_by: 1,
    created_at: "2024-01-01T09:00:00Z",
    updated_at: "2024-01-01T16:45:00Z",
    participants: [
      { user_id: 1, name: "John Doe", role: "admin" },
      { user_id: 2, name: "Jane Smith", role: "member" },
      { user_id: 3, name: "Bob Johnson", role: "member" },
      { user_id: 4, name: "Alice Brown", role: "member" },
    ],
    last_message: "Let's schedule a meeting for tomorrow",
    unread_count: 0,
    is_muted: false,
  },
  {
    conversation_id: 3,
    type: "direct",
    name: null,
    created_by: 3,
    created_at: "2024-01-01T11:00:00Z",
    updated_at: "2024-01-01T14:20:00Z",
    participants: [
      { user_id: 1, name: "John Doe", role: "member" },
      { user_id: 3, name: "Bob Johnson", role: "member" },
    ],
    last_message: "Thanks for the help!",
    unread_count: 1,
    is_muted: false,
  },
  {
    conversation_id: 4,
    type: "group",
    name: "Weekend Plans",
    created_by: 2,
    created_at: "2024-01-01T12:00:00Z",
    updated_at: "2024-01-01T17:10:00Z",
    participants: [
      { user_id: 1, name: "John Doe", role: "member" },
      { user_id: 2, name: "Jane Smith", role: "admin" },
      { user_id: 5, name: "Charlie Wilson", role: "member" },
    ],
    last_message: "Movie at 7 PM?",
    unread_count: 3,
    is_muted: true,
  },
]

export const mockMessages = [
  {
    message_id: 1,
    conversation_id: 1,
    sender_id: 2,
    content: "Hey John! How are you doing?",
    message_type: "text",
    file_data: null,
    is_edited: false,
    edited_at: null,
    reply_to_message_id: null,
    created_at: "2024-01-01T15:00:00Z",
    updated_at: "2024-01-01T15:00:00Z",
    reactions: [
      {
        reaction_id: 1,
        message_id: 1,
        user_id: 1,
        reaction_type: "like",
        created_at: "2024-01-01T15:01:00Z",
      },
    ],
  },
  {
    message_id: 2,
    conversation_id: 1,
    sender_id: 1,
    content: "I'm doing great! Thanks for asking. How about you?",
    message_type: "text",
    file_data: null,
    is_edited: false,
    edited_at: null,
    reply_to_message_id: null,
    created_at: "2024-01-01T15:05:00Z",
    updated_at: "2024-01-01T15:05:00Z",
    reactions: [],
  },
  {
    message_id: 3,
    conversation_id: 1,
    sender_id: 2,
    content: "Pretty good! Just working on some projects.",
    message_type: "text",
    file_data: null,
    is_edited: true,
    edited_at: "2024-01-01T15:31:00Z",
    reply_to_message_id: null,
    created_at: "2024-01-01T15:30:00Z",
    updated_at: "2024-01-01T15:31:00Z",
    reactions: [
      {
        reaction_id: 2,
        message_id: 3,
        user_id: 1,
        reaction_type: "love",
        created_at: "2024-01-01T15:32:00Z",
      },
    ],
  },
  {
    message_id: 4,
    conversation_id: 2,
    sender_id: 1,
    content: "Hey team! Let's discuss our project timeline.",
    message_type: "text",
    file_data: null,
    is_edited: false,
    edited_at: null,
    reply_to_message_id: null,
    created_at: "2024-01-01T16:00:00Z",
    updated_at: "2024-01-01T16:00:00Z",
    reactions: [],
  },
  {
    message_id: 5,
    conversation_id: 2,
    sender_id: 2,
    content: "Sounds good! I have some updates to share.",
    message_type: "text",
    file_data: null,
    is_edited: false,
    edited_at: null,
    reply_to_message_id: null,
    created_at: "2024-01-01T16:15:00Z",
    updated_at: "2024-01-01T16:15:00Z",
    reactions: [
      {
        reaction_id: 3,
        message_id: 5,
        user_id: 1,
        reaction_type: "like",
        created_at: "2024-01-01T16:16:00Z",
      },
      {
        reaction_id: 4,
        message_id: 5,
        user_id: 3,
        reaction_type: "like",
        created_at: "2024-01-01T16:17:00Z",
      },
    ],
  },
  {
    message_id: 6,
    conversation_id: 2,
    sender_id: 3,
    content: "Let's schedule a meeting for tomorrow",
    message_type: "text",
    file_data: null,
    is_edited: false,
    edited_at: null,
    reply_to_message_id: null,
    created_at: "2024-01-01T16:45:00Z",
    updated_at: "2024-01-01T16:45:00Z",
    reactions: [],
  },
  {
    message_id: 7,
    conversation_id: 3,
    sender_id: 3,
    content: "Hey John, can you help me with the database setup?",
    message_type: "text",
    file_data: null,
    is_edited: false,
    edited_at: null,
    reply_to_message_id: null,
    created_at: "2024-01-01T14:00:00Z",
    updated_at: "2024-01-01T14:00:00Z",
    reactions: [],
  },
  {
    message_id: 8,
    conversation_id: 3,
    sender_id: 1,
    content: "I can help you with that. What specific issues are you facing?",
    message_type: "text",
    file_data: null,
    is_edited: false,
    edited_at: null,
    reply_to_message_id: null,
    created_at: "2024-01-01T14:10:00Z",
    updated_at: "2024-01-01T14:10:00Z",
    reactions: [],
  },
  {
    message_id: 9,
    conversation_id: 3,
    sender_id: 3,
    content: "Thanks for the help!",
    message_type: "text",
    file_data: null,
    is_edited: false,
    edited_at: null,
    reply_to_message_id: null,
    created_at: "2024-01-01T14:20:00Z",
    updated_at: "2024-01-01T14:20:00Z",
    reactions: [
      {
        reaction_id: 5,
        message_id: 9,
        user_id: 1,
        reaction_type: "love",
        created_at: "2024-01-01T14:21:00Z",
      },
    ],
  },
]
